{"name": "test_get", "status": "failed", "statusDetails": {"message": "AssertionError: FAILURE: \nassert 166 == 168\ntests/test_cases.py:62 in test_get() -> check.equal(final_size, initial_size+3, \"\")\n------------------------------------------------------------\nFailed Checks: 1", "trace": "FAILURE: \nassert 166 == 168\ntests/test_cases.py:62 in test_get() -> check.equal(final_size, initial_size+3, \"\")\n------------------------------------------------------------\nFailed Checks: 1"}, "start": 1654721729663, "stop": 1654721731035, "uuid": "11f0e671-77b7-490c-a542-03c27507bbb0", "historyId": "2b92b699695a9523974c6c24893482f5", "testCaseId": "7537be7ec288323126f37ef343b9dbe9", "fullName": "tests.test_cases#test_get", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_cases"}, {"name": "host", "value": "KSargsyanL2M"}, {"name": "thread", "value": "55846-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cases"}]}